"""create telemetry points

Revision ID: 288fd4e60068
Revises: de0b8fb08c2c
Create Date: 2026-06-23 00:55:18.023466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '288fd4e60068'
down_revision: Union[str, Sequence[str], None] = 'de0b8fb08c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_points',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('rpm', sa.Integer(), nullable=False),
    sa.Column('speed_mph', sa.Float(), nullable=False),
    sa.Column('throttle_percent', sa.Float(), nullable=False),
    sa.Column('coolant_temp_f', sa.Float(), nullable=False),
    sa.Column('intake_temp_f', sa.Float(), nullable=True),
    sa.Column('boost_psi', sa.Float(), nullable=True),
    sa.Column('fuel_level_percent', sa.Float(), nullable=True),
    sa.Column('battery_voltage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['driving_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_points_session_id'), 'telemetry_points', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_points_session_id'), table_name='telemetry_points')
    op.drop_table('telemetry_points')
    # ### end Alembic commands ###
