"""add csv session metadata

Revision ID: 85a328a0e9aa
Revises: 288fd4e60068
Create Date: 2026-07-08 22:52:45.155807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a328a0e9aa'
down_revision: Union[str, Sequence[str], None] = '288fd4e60068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driving_sessions', sa.Column('selected_metrics', sa.JSON(), nullable=True))
    op.add_column('driving_sessions', sa.Column('csv_file_name', sa.String(), nullable=True))
    op.add_column('driving_sessions', sa.Column('csv_s3_key', sa.String(), nullable=True))
    op.add_column('driving_sessions', sa.Column('csv_s3_url', sa.String(), nullable=True))
    op.add_column('driving_sessions', sa.Column('csv_file_size_bytes', sa.Integer(), nullable=True))
    op.add_column('driving_sessions', sa.Column('sample_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driving_sessions', 'sample_count')
    op.drop_column('driving_sessions', 'csv_file_size_bytes')
    op.drop_column('driving_sessions', 'csv_s3_url')
    op.drop_column('driving_sessions', 'csv_s3_key')
    op.drop_column('driving_sessions', 'csv_file_name')
    op.drop_column('driving_sessions', 'selected_metrics')
    # ### end Alembic commands ###
