"""create driving sessions

Revision ID: de0b8fb08c2c
Revises: a04877749b59
Create Date: 2026-06-22 02:37:15.417573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de0b8fb08c2c'
down_revision: Union[str, Sequence[str], None] = 'a04877749b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driving_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('distance_miles', sa.Float(), nullable=True),
    sa.Column('max_speed_mph', sa.Float(), nullable=False),
    sa.Column('avg_speed_mph', sa.Float(), nullable=True),
    sa.Column('max_rpm', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driving_sessions_vehicle_id'), 'driving_sessions', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_driving_sessions_vehicle_id'), table_name='driving_sessions')
    op.drop_table('driving_sessions')
    # ### end Alembic commands ###
